### ISSUE TITLE
[新增物品]赎罪券

### ISSUE THREAD

**Issue by Libellule505** [auioc/NotEnoughLuck#14]
1. <b>物品id</b>
   - `notenoughluck:indulgence`
2. <b>获取</b>
   - 村民交易<table border="1"><tr><td>职业</td><td>等级</td><td>购买物品</td><td>默认数量</td><td>价格乘数</td><td>出售物品</td><td>数量</td><td>可交易次数</td><td>经验值</td></tr><tr><td>牧师</td><td>大师</td><td>绿宝石</td><td>32</td><td>0.25</td><td>赎罪券</td><td>1</td><td>2</td><td>30</td></tr></table>
3. <b>使用方法</b>
   - 手持赎罪券，长按右键，消耗一个赎罪券，使用者第二天的“运势”等级会上升一级（比如从“大凶”变为“中凶”）。
4. <b>配置文件</b>
   - 禁用赎罪券交易：false。（默认为false）

**Comment by lainio24** [comment]
使用赎罪券物品后获得无法通过食用食物清除的救赎（redemption）效果，在此效果生效期间内，获得霉运效果时倍率-1。
