### ISSUE TITLE
[模组联动]在冠军Champions模组新增精英怪词缀

### ISSUE THREAD

**Issue by Libellule505** [auioc/NotEnoughLuck#19]
- 联动模组：[冠军 (Champions)](https://www.curseforge.com/minecraft/mc-mods/champions)
   - 新增词缀
     - 灾星jinx：被攻击时，随机给予攻击者等级Ⅰ~Ⅲ的霉运，持续5秒。
     - 针刺acupuncture：攻击力下降25%，但无视目标EPF。
     - 驱散dispel：被攻击时移除攻击者一个正面效果。
     - 现实reality：免疫魔法伤害，但受到的其他伤害增加25%。
     - 飓风hurricane：被击杀后将击杀者随机传送到32格内，并给予15秒反胃。

**Comment by Libellule505** [comment]
- 词缀效果修改
     -  灾星jinx：被攻击时，随机给予攻击者等级1~(精英怪等级+1)的霉运，持续5秒。
     - 驱散dispel：攻击时，(50+精英怪等级×10)%概率移除目标一个正面效果。

**Comment by WakelessSloth56** [comment]
此功能将被转移至单独的项目中。
[@auioc/ExtraChampions](https://github.com/auioc/ExtraChampions)
