### ISSUE TITLE
[新增物品]黄历

### ISSUE THREAD

**Issue by Libellule505** [auioc/NotEnoughLuck#2]
1. 物品id
   - almanac
2. 获取
   - 手持四叶草，长按右键。若背包中有365或366张纸（根据现实时间是否处于闰年决定），那么会消耗四叶草和这些纸，获得一本黄历。
3. 使用方法
   - 手持黄历右键，可以打开黄历， 显示昨天、今天、明天的“吉凶”情况。
   - 在黄历界面里，可以输入天数，查看那一天的“吉凶”情况。
4. 配置文件
   - 是否根据现实时间决定制作时消耗纸的数量：true。（默认为true）
   - 制作时消耗纸的数量，如果上一项为true，则此条无效：365。（默认为365）

**Comment by Libellule505** [comment]
修改物品id：tung_shing

**Comment by WakelessSloth56** [comment]
缓存：（ #4 ）
1. 每次打开黄历或在黄历界面中查询运势值时先检查所需的运势值是否在缓存中，有则使用缓存的值，否则请求服务端更新；
2. 在黄历界面中查询时若使用缓存的值，则不会设置黄历为冷却状态。

**Comment by Libellule505** [comment]
冷却提示：
   - 黄历处于冷却中时，点击会提示：“这本老黄历有点年头了，经不起折腾，慢点儿翻。”
