### ISSUE TITLE
[游戏设定]运势

### ISSUE THREAD

**Issue by Libellule505** [auioc/NotEnoughLuck#3]
1. 获得
   - 每天的0点或者玩家出生、重生时，玩家或获得一个反映当天“吉凶”情况的状态效果。
2. 功能
   - 不同的“吉凶”会持续给予玩家幸运或霉运效果。
     1. “大吉”：幸运Ⅳ
     2. “中吉”：幸运Ⅲ
     3. “小吉”：幸运Ⅱ
     4. “末吉”：幸运Ⅰ
     5. “平”：（不给予玩家幸运或霉运）
     6. “末凶”：霉运Ⅰ
     7. “小凶”：霉运Ⅱ
     8. “中凶”：霉运Ⅲ
     9. “大凶”：霉运Ⅳ
3. 特点
   - “吉凶”效果的持续时间是一天。
   - “吉凶”效果本身不会被奶桶或其他状态清除能力解除，只有获得新的“吉凶”效果时，才会移除上一个“吉凶”效果。
   - “吉凶”效果每隔1分钟给予玩家一次幸运或霉运，可以用奶桶清除幸运或霉运效果。
4. 配置文件
   - 是否允许“吉凶”效果被解除：false。（默认为false）

**Comment by Libellule505** [comment]
- 记地图种子值为n，天数为x。那么`|n|^(0.2+|sinx|)≡k(mod37)`，那么：
       1. k=0时：大吉
       2. 1≤k≤2时：中吉
       3. 3≤k≤6时：小吉
       4. 7≤k≤14时：末吉
       5. 15≤k≤24时：平
       6. 25≤k≤30时：末凶
       7. 31≤k≤33时：小凶
       8. 34≤k≤35时：中凶
       9. k=36时：大凶

**Comment by Libellule505** [comment]
公式修改，补充“取整”这一步：
`[|n|^(0.2+|sinx|)]≡k(mod37)`

**Comment by Libellule505** [comment]
<b>名称修改</b>
   - “吉凶”改为“运势”；其余名称不变。

**Comment by WakelessSloth56** [comment]
将原始的运势值(0～36)重新量化为-4～4来依次表示从大凶到大吉的运势。
(5d59a682081df0c0339aefc04a53405a8a951641)

**Comment by lainio24** [comment]
不再使用状态效果，直接使用 `ServerTickEvent`。
间隔更改为 2 分钟。
