### ISSUE TITLE
[新增物品]骰子

### ISSUE THREAD

**Issue by Libellule505** [auioc/NotEnoughLuck#6]
1. 物品id
   - `notenoughluck:dice`
2. 获取
   - 无序合成：<table border="1"><tr><td>石头</td><td>四叶草</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr><tr><td>-</td><td>-</td><td>-</td></tr></table>
3. 使用方法
   - 手持骰子右键，骰子会掉落，捡起时骰子会显示掷得的点数，移除身上的幸运和霉运效果，然后根据点数：
    1. 获得霉运Ⅲ；
    2. 获得霉运Ⅱ；
    3. 获得霉运Ⅰ；
    4. 获得幸运Ⅰ；
    5. 获得幸运Ⅱ；
    6. 获得幸运Ⅲ。
 这些效果均持续1分钟。骰子的使用会有15分钟的公共冷却。
4.  配置文件
    - 使用骰子是否移除已有的幸运和霉运效果：true。（默认为true）
    - 通过骰子获得幸运或霉运持续时间：60秒。（默认为60秒）
    - 骰子的使用冷却时长：900秒。（默认为900秒）

**Comment by WakelessSloth56** [comment]
> ~~手持骰子右键，骰子会掉落，捡起时骰子会显示掷得的点数~~
* 丢出骰子，为掉落物状态的骰子即显示点数，点数面向上；
* 玩家捡起骰子后会在 GUI 中显示点数；
* 非玩家丢出所创建（投掷器掷出、破坏容器的掉落等）的掉落物以及其在 GUI 中不会显示点数，六面均显示为“？”。
